# Generated by Django 4.0.4 on 2022-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_password_news_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
